// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu_ZhkXz9pF48i5wCFzCGqdfYYx9OkH_8',
    appId: '1:20459132617:android:827702c7e87827dea35f18',
    messagingSenderId: '20459132617',
    projectId: 'proyecto-desarrollo-movi-47954',
    storageBucket: 'proyecto-desarrollo-movi-47954.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC466tAyAcUukI6ZmqffPb3MWwTzt3RJ2g',
    appId: '1:20459132617:web:189cc42040866703a35f18',
    messagingSenderId: '20459132617',
    projectId: 'proyecto-desarrollo-movi-47954',
    authDomain: 'proyecto-desarrollo-movi-47954.firebaseapp.com',
    storageBucket: 'proyecto-desarrollo-movi-47954.firebasestorage.app',
    measurementId: 'G-F0QQFSGJZM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpSb155_qLa9uZzSz2_Kw3SGoFfbw_yc',
    appId: '1:20459132617:ios:6c0acc19d8fe6179a35f18',
    messagingSenderId: '20459132617',
    projectId: 'proyecto-desarrollo-movi-47954',
    storageBucket: 'proyecto-desarrollo-movi-47954.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpSb155_qLa9uZzSz2_Kw3SGoFfbw_yc',
    appId: '1:20459132617:ios:6c0acc19d8fe6179a35f18',
    messagingSenderId: '20459132617',
    projectId: 'proyecto-desarrollo-movi-47954',
    storageBucket: 'proyecto-desarrollo-movi-47954.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC466tAyAcUukI6ZmqffPb3MWwTzt3RJ2g',
    appId: '1:20459132617:web:567c67246249f891a35f18',
    messagingSenderId: '20459132617',
    projectId: 'proyecto-desarrollo-movi-47954',
    authDomain: 'proyecto-desarrollo-movi-47954.firebaseapp.com',
    storageBucket: 'proyecto-desarrollo-movi-47954.firebasestorage.app',
    measurementId: 'G-NNBGEFGPEK',
  );

}